# Build settings
[build]
  base = "/opt/build/repo/public"
  publish = "/opt/build/repo/public"
  command = "php index.php"
  functions = "functions"

# Deployment settings
[build.environment]
  # Specify the PHP version
  PHP_VERSION = "8.1"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.php/:splat"
  status = 200

# Asset optimization and settings
[build.processing]
  # Specify asset optimization settings if needed

# Headers settings
[[headers]]
  # Define headers, such as for security policies
  # For example, Content Security Policy (CSP) header
  for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self';"

# Basic server settings
[dev]
  # Specify the port for local development server
  port = 8000
